// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9MLeqnF-mbwCl8Ob1-NYFy8wS7Qdp7t4',
    appId: '1:1080119744318:web:7153d9112ee2f473fafe6f',
    messagingSenderId: '1080119744318',
    projectId: 'fitness-1eda0',
    authDomain: 'fitness-1eda0.firebaseapp.com',
    storageBucket: 'fitness-1eda0.appspot.com',
    measurementId: 'G-D8BL32Z1HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDkZabTdHS9bJ35QXEIUUqZymJ1Z1hMzQ',
    appId: '1:1080119744318:android:0f2b762676c30356fafe6f',
    messagingSenderId: '1080119744318',
    projectId: 'fitness-1eda0',
    storageBucket: 'fitness-1eda0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1NtH3T2imxEn_2iq5-a3gFbOYLe9yqwc',
    appId: '1:1080119744318:ios:75b4fd4769dd3bdbfafe6f',
    messagingSenderId: '1080119744318',
    projectId: 'fitness-1eda0',
    storageBucket: 'fitness-1eda0.appspot.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1NtH3T2imxEn_2iq5-a3gFbOYLe9yqwc',
    appId: '1:1080119744318:ios:75b4fd4769dd3bdbfafe6f',
    messagingSenderId: '1080119744318',
    projectId: 'fitness-1eda0',
    storageBucket: 'fitness-1eda0.appspot.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9MLeqnF-mbwCl8Ob1-NYFy8wS7Qdp7t4',
    appId: '1:1080119744318:web:ec5abb5a2359ad9ffafe6f',
    messagingSenderId: '1080119744318',
    projectId: 'fitness-1eda0',
    authDomain: 'fitness-1eda0.firebaseapp.com',
    storageBucket: 'fitness-1eda0.appspot.com',
    measurementId: 'G-P2F8ZD6B69',
  );
}
